# Training Pipeline Configuration
# Two-Phase Training System with Regime-Based Model Selection

# Storage settings
storage:
  artifacts_dir: "./artifacts"
  checkpoints_dir: "./checkpoints/training_pipeline"
  max_checkpoint_age_days: 30  # Auto-delete old checkpoints
  compress_old_models: true     # Compress models older than 30 days

# Queue settings
queue:
  max_parallel_queues: 1        # Max simultaneous queues
  auto_checkpoint_interval: 10  # Checkpoint every N models
  max_inference_workers: 4      # Parallel inference backtests

# Recovery settings
recovery:
  auto_resume_on_crash: false   # Auto-resume interrupted queues
  detect_crash_after_minutes: 5 # Consider crashed if no activity for N minutes

# Model file management
model_management:
  delete_non_best_models: true  # Delete models not best for any regime
  keep_top_n_per_regime: 1      # Keep top N models per regime
  min_improvement_threshold: 0.01  # Min improvement % to replace best model

# Performance settings
performance:
  model_cache_size_mb: 1000     # Cache recent models in memory
  database_connection_pool_size: 5
  batch_insert_size: 100        # Batch size for database inserts

# Regime definitions (loaded into database on first run)
regimes:
  - name: "bull_trending"
    description: "Strong upward trend with positive momentum"
    detection_rules:
      trend_strength: "> 0.7"
      returns: "> 0"

  - name: "bear_trending"
    description: "Strong downward trend with negative momentum"
    detection_rules:
      trend_strength: "> 0.7"
      returns: "< 0"

  - name: "volatile_ranging"
    description: "High volatility without clear trend direction"
    detection_rules:
      trend_strength: "< 0.3"
      volatility: "> 75th percentile"

  - name: "calm_ranging"
    description: "Low volatility consolidation period"
    detection_rules:
      trend_strength: "< 0.3"
      volatility: "< 50th percentile"

# Inference grid defaults
inference_grid:
  prediction_methods:
    - "direct"           # Single-step prediction
    - "recursive"        # Multi-step recursive
    - "direct_multi"     # Multiple direct predictors

  ensemble_methods:
    - "mean"            # Simple average
    - "weighted"        # Performance-weighted
    - "stacking"        # Meta-model stacking

  confidence_thresholds:
    - 0.0   # No threshold
    - 0.3   # Low confidence
    - 0.5   # Medium confidence
    - 0.7   # High confidence
    - 0.9   # Very high confidence

  lookback_windows:
    - 50    # Short lookback
    - 100   # Medium lookback
    - 200   # Long lookback

# Training configuration defaults
training_defaults:
  validation_split: 0.2
  test_split: 0.1
  random_state: 42
  n_jobs: -1  # Use all CPU cores
  verbose: 1

# Regime detection parameters
regime_detection:
  trend_window: 50          # Bars for trend calculation
  volatility_window: 20     # Bars for volatility calculation
  returns_window: 10        # Bars for returns calculation
  min_regime_duration: 10   # Min bars to classify as regime

# Metrics configuration
metrics:
  primary_metric: "sharpe_ratio"  # Used for regime best model selection
  secondary_metrics:
    - "max_drawdown"
    - "win_rate"
    - "profit_factor"
    - "sortino_ratio"
    - "calmar_ratio"

  # Thresholds for "good" performance
  thresholds:
    min_sharpe_ratio: 0.5
    max_drawdown: -0.3
    min_win_rate: 0.45
    min_profit_factor: 1.2

# Notification settings (optional)
notifications:
  enabled: false
  email_on_queue_complete: false
  email_on_queue_failure: false
  email_on_new_regime_best: false

# Logging configuration
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR
  log_to_file: true
  log_file: "./logs/training_pipeline.log"
  max_log_size_mb: 100
  backup_count: 5
