patterns:
  enabled: true
  auto_scan_on_scroll: true
  detect_on_new_bar: true
  historical_scan:
    enabled_default: false
    past_extra_bars: 2000
  chart_patterns:
    enabled_default: true
    keys_enabled:
    - broadening_bottom
    - broadening_top
    - right_angle_broadening_ascending
    - right_angle_broadening_descending
    - broadening_wedge_ascending
    - broadening_wedge_descending
    - wedge_ascending
    - wedge_descending
    - ascending_triangle
    - descending_triangle
    - symmetrical_triangle
    - rectangle_range
    - diamond_top
    - diamond_bottom
    - double_top
    - double_bottom
    - triple_bottom
    - triple_top
    - rising_channel
    - falling_channel
    - bull_flag
    - bull_pennant
    - bear_flag
    - bear_pennant
    - head_and_shoulders
    - inverse_head_and_shoulders
    - elliott_impulse_bull
    - elliott_impulse_bear
    - elliott_corrective_abc
    - gartley_bull
    - gartley_bear
    - butterfly_bull
    - butterfly_bear
    - bat_bull
    - bat_bear
    - crab_bull
    - crab_bear
    - cypher_bull
    - cypher_bear
    - shark_bull
    - shark_bear
    - abcd_bull
    - abcd_bear
    - rounding_bottom
    - rounding_top
    - island_reversal_top
    - measured_move
    - island_reversal_bottom
    - three_drives
    parameter_overrides:
      broadening_bottom: {}
      broadening_top: {}
      right_angle_broadening_ascending: {}
      right_angle_broadening_descending: {}
      broadening_wedge_ascending: {}
      broadening_wedge_descending: {}
      wedge_ascending: {}
      wedge_descending: {}
      ascending_triangle: {}
      descending_triangle: {}
      symmetrical_triangle: {}
      rectangle_range: {}
      diamond_top: {}
      diamond_bottom: {}
      double_top: {}
      double_bottom: {}
      triple_bottom: {}
      triple_top: {}
      rising_channel: {}
      falling_channel: {}
      bull_flag: {}
      bull_pennant: {}
      bear_flag: {}
      bear_pennant: {}
      head_and_shoulders: {}
      inverse_head_and_shoulders: {}
      elliott_impulse_bull: {}
      elliott_impulse_bear: {}
      elliott_corrective_abc: {}
      gartley_bull: {}
      gartley_bear: {}
      butterfly_bull: {}
      butterfly_bear: {}
      bat_bull: {}
      bat_bear: {}
      crab_bull: {}
      crab_bear: {}
      cypher_bull: {}
      cypher_bear: {}
      shark_bull: {}
      shark_bear: {}
      abcd_bull: {}
      abcd_bear: {}
      rounding_bottom: {}
      rounding_top: {}
      island_reversal_top: {}
      measured_move: {}
      island_reversal_bottom: {}
      three_drives: {}
  candle_patterns:
    enabled_default: true
    keys_enabled:
    - hammer
    - shooting_star
    - bullish_engulfing
    - bearish_engulfing
    - doji
    - dragonfly_doji
    - gravestone_doji
    - three_white_soldiers
    - three_black_crows
    - morning_star
    - evening_star
    - abandoned_baby_bull
    - abandoned_baby_bear
    - three_line_strike_bull
    - three_line_strike_bear
    - three_inside_up
    - three_inside_down
    - three_outside_up
    - three_outside_down
    - unique_three_river_bottom
    - unique_three_river_top
    - concealing_baby_swallow
    params:
      bearish_engulfing:
        confirm_with_volume: false
        rr: 1.5
        target_mode: Altezza figura
      dragonfly_doji:
        confirm_with_volume: false
        rr: 1.5
        target_mode: Altezza figura
      tweezer_bottom:
        confirm_with_volume: false
        rr: 1.5
        target_mode: Altezza figura
      shooting_star:
        confirm_with_volume: false
        rr: 1.5
        target_mode: Altezza figura
      bullish_engulfing:
        confirm_with_volume: false
        rr: 1.5
        target_mode: Altezza figura
      harami_bear:
        confirm_with_volume: false
        rr: 1.5
        target_mode: Altezza figura
      three_black_crows:
        confirm_with_volume: false
        rr: 1.5
        target_mode: Altezza figura
      rising_three_methods:
        confirm_with_volume: false
        rr: 1.5
        target_mode: Altezza figura
      falling_three_methods:
        confirm_with_volume: false
        rr: 1.5
        target_mode: Altezza figura
      dark_cloud_cover:
        confirm_with_volume: false
        rr: 1.5
        target_mode: Altezza figura
      piercing_line:
        confirm_with_volume: false
        rr: 1.5
        target_mode: Altezza figura
      gravestone_doji:
        confirm_with_volume: false
        rr: 1.5
        target_mode: Altezza figura
      tweezer_top:
        confirm_with_volume: false
        rr: 1.5
        target_mode: Altezza figura
      harami_bull:
        confirm_with_volume: false
        rr: 1.5
        target_mode: Altezza figura
      hammer:
        confirm_with_volume: false
        rr: 1.5
        target_mode: Altezza figura
      three_white_soldiers:
        confirm_with_volume: false
        rr: 1.5
        target_mode: Altezza figura
      harami_cross_bull:
        confirm_with_volume: false
      harami_cross_bear:
        confirm_with_volume: false
      belt_hold_bull:
        confirm_with_volume: false
      belt_hold_bear:
        confirm_with_volume: false
      mat_hold_bull:
        confirm_with_volume: false
      mat_hold_bear:
        confirm_with_volume: false
      kicker_bull:
        confirm_with_volume: false
      kicker_bear:
        confirm_with_volume: false
      tasuki_bull:
        confirm_with_volume: false
      tasuki_bear:
        confirm_with_volume: false
      morning_star:
        confirm_with_volume: false
      evening_star:
        confirm_with_volume: false
      abandoned_baby_bull:
        confirm_with_volume: false
      abandoned_baby_bear:
        confirm_with_volume: false
      three_line_strike_bull:
        confirm_with_volume: false
      three_line_strike_bear:
        confirm_with_volume: false
      three_inside_up:
        confirm_with_volume: false
      three_inside_down:
        confirm_with_volume: false
      three_outside_up:
        confirm_with_volume: false
      three_outside_down:
        confirm_with_volume: false
      unique_three_river_bottom:
        confirm_with_volume: false
      unique_three_river_top:
        confirm_with_volume: false
      concealing_baby_swallow:
        confirm_with_volume: false
      identical_three_crows:
        confirm_with_volume: false
    parameter_overrides:
      hammer: {}
      identical_three_crows: {}
      shooting_star: {}
      bullish_engulfing: {}
      bearish_engulfing: {}
      doji: {}
      dragonfly_doji: {}
      gravestone_doji: {}
      three_white_soldiers: {}
      three_black_crows: {}
      morning_star: {}
      evening_star: {}
      abandoned_baby_bull: {}
      abandoned_baby_bear: {}
      three_line_strike_bull: {}
      three_line_strike_bear: {}
      three_inside_up: {}
      three_inside_down: {}
      three_outside_up: {}
      three_outside_down: {}
      unique_three_river_bottom: {}
      unique_three_river_top: {}
      concealing_baby_swallow: {}
  view:
    badge_info: true
    badge_font_pt: 8
    overlay_alpha: 0.6
    arrow_len_atr: 1.5
  current_scan:
    lookback_hours: 6
    interval_seconds: 10
dataset_strategy: profittabilità
historical_patterns:
  enabled: true
  start_time: 5d
  end_time: 1d
performance:
  detection_threads: 18
  detection_mode: max_speed
  parallel_historical: true
  parallel_realtime: true
