patterns:
  enabled: true
  auto_scan_on_scroll: true
  detect_on_new_bar: true
  historical_scan:
    enabled_default: false
    past_extra_bars: 2000
  chart_patterns:
    enabled_default: true
    keys_enabled:
    - broadening_bottom
    - broadening_top
    - right_angle_broadening_ascending
    - right_angle_broadening_descending
    - broadening_wedge_ascending
    - broadening_wedge_descending
    - wedge_ascending
    - wedge_descending
    - ascending_triangle
    - descending_triangle
    - symmetrical_triangle
    - rectangle_range
    - diamond_top
    - diamond_bottom
    - double_top
    - double_bottom
    - triple_top
    - triple_bottom
    - rising_channel
    - falling_channel
    - bull_flag
    - bear_flag
    - bull_pennant
    - bear_pennant
    - head_and_shoulders
    parameter_overrides:
      broadening_bottom: {}
      broadening_top: {}
      right_angle_broadening_ascending: {}
      right_angle_broadening_descending: {}
      broadening_wedge_ascending: {}
      broadening_wedge_descending: {}
      wedge_ascending: {}
      wedge_descending: {}
      ascending_triangle: {}
      descending_triangle: {}
      symmetrical_triangle: {}
      rectangle_range: {}
      diamond_top: {}
      diamond_bottom: {}
      double_top: {}
      double_bottom: {}
      triple_top: {}
      triple_bottom: {}
      rising_channel: {}
      falling_channel: {}
      bull_flag: {}
      bear_flag: {}
      bull_pennant: {}
      bear_pennant: {}
      head_and_shoulders: {}
      inverse_head_and_shoulders: {}
  candle_patterns:
    enabled_default: true
    keys_enabled:
    - hammer
    - shooting_star
    - bearish_engulfing
    - bullish_engulfing
    - harami_bull
    - harami_bear
    - three_white_soldiers
    - three_black_crows
    - dark_cloud_cover
    - piercing_line
    - dragonfly_doji
    - gravestone_doji
    - tweezer_top
    - tweezer_bottom
    - rising_three_methods
    - falling_three_methods
    - harami_cross_bull
    - harami_cross_bear
    - belt_hold_bull
    - belt_hold_bear
    - mat_hold_bull
    - mat_hold_bear
    - kicker_bull
    - kicker_bear
    - tasuki_bull
    - tasuki_bear
    - morning_star
    - evening_star
    - abandoned_baby_bull
    - abandoned_baby_bear
    - three_line_strike_bull
    - three_line_strike_bear
    - three_inside_up
    - three_inside_down
    - three_outside_up
    - unique_three_river_bottom
    - three_outside_down
    - unique_three_river_top
    - concealing_baby_swallow
    - identical_three_crows
    params:
      bearish_engulfing:
        confirm_with_volume: false
        rr: 1.5
        target_mode: Altezza figura
      dragonfly_doji:
        confirm_with_volume: false
        rr: 1.5
        target_mode: Altezza figura
      tweezer_bottom:
        confirm_with_volume: false
        rr: 1.5
        target_mode: Altezza figura
      shooting_star:
        confirm_with_volume: false
        rr: 1.5
        target_mode: Altezza figura
      bullish_engulfing:
        confirm_with_volume: false
        rr: 1.5
        target_mode: Altezza figura
      harami_bear:
        confirm_with_volume: false
        rr: 1.5
        target_mode: Altezza figura
      three_black_crows:
        confirm_with_volume: false
        rr: 1.5
        target_mode: Altezza figura
      rising_three_methods:
        confirm_with_volume: false
        rr: 1.5
        target_mode: Altezza figura
      falling_three_methods:
        confirm_with_volume: false
        rr: 1.5
        target_mode: Altezza figura
      dark_cloud_cover:
        confirm_with_volume: false
        rr: 1.5
        target_mode: Altezza figura
      piercing_line:
        confirm_with_volume: false
        rr: 1.5
        target_mode: Altezza figura
      gravestone_doji:
        confirm_with_volume: false
        rr: 1.5
        target_mode: Altezza figura
      tweezer_top:
        confirm_with_volume: false
        rr: 1.5
        target_mode: Altezza figura
      harami_bull:
        confirm_with_volume: false
        rr: 1.5
        target_mode: Altezza figura
      hammer:
        confirm_with_volume: false
        rr: 1.5
        target_mode: Altezza figura
      three_white_soldiers:
        confirm_with_volume: false
        rr: 1.5
        target_mode: Altezza figura
    parameter_overrides:
      hammer: {}
      shooting_star: {}
      bearish_engulfing: {}
      bullish_engulfing: {}
      harami_bull: {}
      harami_bear: {}
      three_white_soldiers: {}
      three_black_crows: {}
      dark_cloud_cover: {}
      piercing_line: {}
      dragonfly_doji: {}
      gravestone_doji: {}
      tweezer_top: {}
      tweezer_bottom: {}
      rising_three_methods: {}
      falling_three_methods: {}
      harami_cross_bull: {}
      harami_cross_bear: {}
      belt_hold_bull: {}
      belt_hold_bear: {}
      mat_hold_bull: {}
      mat_hold_bear: {}
      kicker_bull: {}
      kicker_bear: {}
      tasuki_bull: {}
      tasuki_bear: {}
      morning_star: {}
      evening_star: {}
      abandoned_baby_bull: {}
      abandoned_baby_bear: {}
      three_line_strike_bull: {}
      three_line_strike_bear: {}
      three_inside_up: {}
      three_inside_down: {}
      three_outside_up: {}
      unique_three_river_bottom: {}
      three_outside_down: {}
      unique_three_river_top: {}
      concealing_baby_swallow: {}
      identical_three_crows: {}
  view:
    badge_info: true
    badge_font_pt: 8
    overlay_alpha: 0.6
    arrow_len_atr: 1.5
  current_scan:
    lookback_hours: 6
    interval_minutes: 5
dataset_strategy: profittabilità
historical_patterns:
  enabled: true
  start_time: 30d
  end_time: 7d
performance:
  detection_threads: 32
  detection_mode: balanced
  parallel_historical: true
  parallel_realtime: true
