patterns:
  enabled: true
  auto_scan_on_scroll: true
  detect_on_new_bar: true
  historical_scan:
    enabled_default: false
    past_extra_bars: 2000
  chart_patterns:
    enabled_default: true
    keys_enabled:
      - broadening_bottom
      - broadening_top
      - right_angle_broadening_ascending
      - right_angle_broadening_descending
      - broadening_wedge_ascending
      - broadening_wedge_descending
  candle_patterns:
    enabled_default: true
    keys_enabled:
      - hammer
      - shooting_star
      - bullish_engulfing
      - bearish_engulfing
      - harami_bull
      - harami_bear
  view:
    badge_info: true
    badge_font_pt: 8
    overlay_alpha: 0.6
    arrow_len_atr: 1.5
